[package]
name = "splinterm"
description = "Wayland terminal emulator and client for Splinterm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
fontdb.workspace = true
rustix.workspace = true
serde.workspace = true
serde_json.workspace = true
splinterm-core = { path = "../splinterm-core" }
splinterm-protocol = { path = "../splinterm-protocol" }
smithay-client-toolkit.workspace = true
swash.workspace = true
tokio.workspace = true
unicode-width.workspace = true
wayland-client.workspace = true

[lints]
workspace = true
