[package]
name = "splinterm-freetype"
description = "Bounded FreeType grayscale raster bridge for Splinterm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
freetype-rs.workspace = true
splinterm-pixman = { path = "../splinterm-pixman" }
thiserror.workspace = true

[lints]
workspace = true
