//! Generated, collision-safe opt-in shell integration.

use std::{
    fs::{self, OpenOptions},
    io::Write,
    os::unix::fs::OpenOptionsExt,
    path::PathBuf,
};

use anyhow::{Context, Result};

use splinterm::config::default_config_dir;

use super::commands::{IntegrationShell, ShellIntegration};

const OMARCHY_BASH: &str = r#"# shellcheck shell=bash
# Generated by Splinterm. Source this file explicitly; it never edits shell startup files.
# Splinterm uses s* names so Omarchy's existing tmux aliases and functions remain untouched.

if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
    printf 'splinterm: source this file from Bash instead of executing it\n' >&2
    exit 2
fi

__splinterm_omarchy_conflicts=()
for __splinterm_omarchy_name in s sdl sds sdlm ssl; do
    __splinterm_omarchy_kind=$(type -t -- "$__splinterm_omarchy_name" 2>/dev/null || true)
    if [[ -n "$__splinterm_omarchy_kind" ]]; then
        __splinterm_omarchy_conflicts+=("$__splinterm_omarchy_name ($__splinterm_omarchy_kind)")
    fi
done

if (( ${#__splinterm_omarchy_conflicts[@]} != 0 )); then
    printf 'splinterm: shell integration not loaded; existing names would be replaced:\n' >&2
    printf '  %s\n' "${__splinterm_omarchy_conflicts[@]}" >&2
    unset __splinterm_omarchy_conflicts __splinterm_omarchy_name __splinterm_omarchy_kind
    return 1
fi

unset __splinterm_omarchy_conflicts __splinterm_omarchy_name __splinterm_omarchy_kind

s() {
    if (( $# != 0 )); then
        printf 'usage: s\n' >&2
        return 2
    fi
    command splinterm preset run omarchy.t
}

sdl() {
    if (( $# < 1 || $# > 2 )); then
        printf 'usage: sdl AI [AI2]\n' >&2
        return 2
    fi
    local -a splinterm_args=(preset run omarchy.tdl --param "ai=$1")
    if (( $# == 2 )); then
        splinterm_args+=(--param "ai2=$2")
    fi
    command splinterm "${splinterm_args[@]}"
}

sds() {
    if (( $# != 0 )); then
        printf 'usage: sds\n' >&2
        return 2
    fi
    command splinterm preset run omarchy.tds
}

sdlm() {
    if (( $# < 1 || $# > 2 )); then
        printf 'usage: sdlm AI [AI2]\n' >&2
        return 2
    fi
    local -a splinterm_args=(preset run omarchy.tdlm --param "ai=$1")
    if (( $# == 2 )); then
        splinterm_args+=(--param "ai2=$2")
    fi
    command splinterm "${splinterm_args[@]}"
}

ssl() {
    if (( $# != 2 )); then
        printf 'usage: ssl COUNT COMMAND\n' >&2
        return 2
    fi
    command splinterm preset run omarchy.tsl --param "count=$1" --param "command=$2"
}
"#;

#[must_use]
pub(super) const fn render(integration: ShellIntegration, shell: IntegrationShell) -> &'static str {
    match (integration, shell) {
        (ShellIntegration::Omarchy, IntegrationShell::Bash) => OMARCHY_BASH,
    }
}

pub(super) fn install(integration: ShellIntegration, shell: IntegrationShell) -> Result<PathBuf> {
    let destination = install_path(integration, shell);
    let parent = destination
        .parent()
        .context("shell integration destination has no parent")?;
    fs::create_dir_all(parent)
        .with_context(|| format!("create shell integration directory {}", parent.display()))?;

    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&destination)
        .with_context(|| {
            format!(
                "refuse to replace existing shell integration {}",
                destination.display()
            )
        })?;
    if let Err(error) = file
        .write_all(render(integration, shell).as_bytes())
        .and_then(|()| file.sync_all())
    {
        drop(file);
        let _ = fs::remove_file(&destination);
        return Err(error)
            .with_context(|| format!("write shell integration {}", destination.display()));
    }
    Ok(destination)
}

#[must_use]
pub(super) fn install_path(integration: ShellIntegration, shell: IntegrationShell) -> PathBuf {
    match (integration, shell) {
        (ShellIntegration::Omarchy, IntegrationShell::Bash) => {
            default_config_dir().join("shell").join("omarchy.bash")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_bash_uses_only_the_s_namespace_and_direct_cli_calls() {
        let script = render(ShellIntegration::Omarchy, IntegrationShell::Bash);
        for name in ["s", "sdl", "sds", "sdlm", "ssl"] {
            assert!(script.contains(&format!("{name}() {{")));
        }
        for name in ["t", "tdl", "tds", "tdlm", "tsl", "ic", "ix", "icx"] {
            assert!(!script.contains(&format!("{name}() {{")));
        }
        assert!(script.contains("command splinterm"));
        assert!(!script.contains("eval "));
        assert!(!script.contains("sh -c"));
        assert!(!script.contains(".bashrc"));
    }
}
