// @generated by tools/benchmark/generate-semantic-fixture-vectors.py; do not edit.
#[rustfmt::skip]
const FIXTURES: &[Fixture] = &[
    Fixture {
        id: "cursor-position",
        foot_commit: "3c5b584b0eafa772eb4376fb6eaf6643399e190e",
        verification: "oracle_verified",
        columns: 6,
        rows: 3,
        input: b"abc\x1b[2;3HZ",
        cursor: ExpectedCursor { column: 3, row: 1, deferred_wrap: false },
        expected_rows: &[
            ExpectedRow { text: "abc   ", linebreak: true },
            ExpectedRow { text: "  Z   ", linebreak: true },
            ExpectedRow { text: "      ", linebreak: true },
        ],
        attribute_runs: &[
        ],
        expected_event_count: 0,
    },
    Fixture {
        id: "erase-line",
        foot_commit: "3c5b584b0eafa772eb4376fb6eaf6643399e190e",
        verification: "oracle_verified",
        columns: 8,
        rows: 3,
        input: b"abcdef\x1b[3D\x1b[K",
        cursor: ExpectedCursor { column: 3, row: 0, deferred_wrap: false },
        expected_rows: &[
            ExpectedRow { text: "abc     ", linebreak: true },
            ExpectedRow { text: "        ", linebreak: true },
            ExpectedRow { text: "        ", linebreak: true },
        ],
        attribute_runs: &[
        ],
        expected_event_count: 0,
    },
    Fixture {
        id: "printable-text",
        foot_commit: "3c5b584b0eafa772eb4376fb6eaf6643399e190e",
        verification: "oracle_verified",
        columns: 8,
        rows: 3,
        input: b"hello",
        cursor: ExpectedCursor { column: 5, row: 0, deferred_wrap: false },
        expected_rows: &[
            ExpectedRow { text: "hello   ", linebreak: true },
            ExpectedRow { text: "        ", linebreak: true },
            ExpectedRow { text: "        ", linebreak: true },
        ],
        attribute_runs: &[
        ],
        expected_event_count: 0,
    },
    Fixture {
        id: "sgr-basic",
        foot_commit: "3c5b584b0eafa772eb4376fb6eaf6643399e190e",
        verification: "oracle_verified",
        columns: 4,
        rows: 2,
        input: b"\x1b[1;31mR\x1b[0mN",
        cursor: ExpectedCursor { column: 2, row: 0, deferred_wrap: false },
        expected_rows: &[
            ExpectedRow { text: "RN  ", linebreak: true },
            ExpectedRow { text: "    ", linebreak: true },
        ],
        attribute_runs: &[
            ExpectedAttributeRun { row: 0, start: 0, end: 1, attributes: ExpectedAttributes { bold: true, dim: false, italic: false, underline: false, blink: false, reverse: false, conceal: false, strikethrough: false, foreground: Some(ExpectedColor { source: ExpectedColorSource::Base16, value: 1 }), background: None } },
        ],
        expected_event_count: 0,
    },
    Fixture {
        id: "soft-wrap",
        foot_commit: "3c5b584b0eafa772eb4376fb6eaf6643399e190e",
        verification: "oracle_verified",
        columns: 5,
        rows: 3,
        input: b"abcdef",
        cursor: ExpectedCursor { column: 1, row: 1, deferred_wrap: false },
        expected_rows: &[
            ExpectedRow { text: "abcde", linebreak: false },
            ExpectedRow { text: "f    ", linebreak: true },
            ExpectedRow { text: "     ", linebreak: true },
        ],
        attribute_runs: &[
        ],
        expected_event_count: 0,
    },
];
