[package]
name = "splinterm-relay"
description = "Bounded stdio transport for remote Splinterm automation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow.workspace = true
nix.workspace = true
rustix.workspace = true
splinterm-graphical-relay = { path = "../splinterm-graphical-relay" }
tokio = { workspace = true, features = ["io-std"] }
tokio-util.workspace = true

[lints]
workspace = true
